steps:
# Step 1: Build the Maven application and create the JAR file
- name: 'maven:3.6.3-openjdk-11'
  entrypoint: 'mvn'
  args: ['package', '-DskipTests']  # Adjust Maven goals/options as needed

# Step 2: Copy the JAR file to a directory accessible to Cloud Build
- name: 'gcr.io/cloud-builders/gsutil'
  #args: ['cp', 'app/target/*.jar', 'gs://dotnetcore8app-artifacts/artifacts/$REPO_NAME/$BUILD_ID/']  
  args: ['cp', '-r', 'target/*.jar', 'gs://dotnetcore8app-artifacts/artifacts/$REPO_NAME/$BUILD_ID/'] 	
artifacts:
  objects:
    location: 'gs://dotnetcore8app-artifacts/artifacts/'  # Replace <your-bucket> with your actual GCS bucket
    paths: ['target/*.jar'] 
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'  # Optional: Customize the timeout if needed