---
steps:
  - name: maven:3.8.4-jdk-11
    entrypoint: mvn
    args:
      - clean
      - install
      - -DskipTests
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/devops-hangout/maven-app/my-maven-app:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/devops-hangout/maven-app/my-maven-app:latest
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - my-maven-app
      - --image
      - gcr.io/devops-hangout/maven-app/my-maven-app:latest
      - --platform
      - managed
      - --region
      - us-central1
      - --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
